**Content Produced by UF Signal Processing Society**

**Authors: Awwab Azam**

# Intro to Deep Learning using PyTorch

This is the first of a planned 3-part series covering the basics of deep learning for applications in Physics and Engineering. In this workshop, we will learn how to use PyTorch to train a very simple neural network, as well as some hand-wavy ML theory. Let's get started!

### Setup

For this tutorial, we will need several Python packages, including PyTorch, NumPy, and MatplotLib. If you are not very tech-savvy, the easiest thing to do would be to open this notebook in Google Colab using the link at the top. Google Colab is an online cloud-based development environment that comes with all these packages preinstalled.

For those who are comfortable working with Python virtual environments and would like to run the code locally, please make sure you have all the packages in the import section installed.

## 0. Getting started

First we need to import the packages that we want to use.

In [1]:
# imports
import torch
import numpy as np

## 1. Tensors

The foundational building block in PyTorch is a tensor, which is basically a multidimensional array. You can make a tensor in several ways, as follows. Random tensors are often useful if you want dummy data to test your model.

In [2]:
# a tensor of zeroes
zero_tensor = torch.zeros(2, 2)
# a tensor of ones
ones_tensor = torch.ones(2, 2)
# a tensor of random numbers
randn_tensor = torch.randn(2, 2)

print(zero_tensor)
print(ones_tensor)
print(randn_tensor)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[-0.7436,  1.0358],
        [-0.9448,  1.4856]])


You can also make a tensor from a NumPy array and vice versa. The PyTorch tensor and the NumPy array will share the same underlying memory, so be careful if you change anything!

In [8]:
np_arr = np.random.random((2, 2))
# should be random
print(np_arr)

tensor = torch.from_numpy(np_arr)
tensor[0, 0] = 0
# should have a zero in the top left corner
print(np_arr)

# notice that we never directly modified np_arr!

[[0.25227843 0.86431116]
 [0.21645239 0.89138967]]
[[0.         0.86431116]
 [0.21645239 0.89138967]]


### Indexing and slicing

If you're familiar with NumPy, PyTorch indexing/slicing is quite similar. If not, no problem, we'll go through it step-by-step.

First things first: Python is 0-indexed, which means that the first element of any dimension in a tensor (or array, or list, etc) IS 0, NOT 1. You can ask a specific element by using the syntax `T[i]` where T is an arbitrary 1D tensor and i is the (0-based) index. If you have more dimensions, you can simply use more indices, i.e. `T[x, y, z]` for a 3D tensor.

Also, keep in mind that (just like in linear algebra), Python is row-major, so e.g. for 2D arrays, the first index determines the **row** and the second index determined the **column**.

You can use a colon : to select all elements in a certain dimension, and an ellipsis ... to select all elements from an unspecified number of dimensions.

In [ ]:
# make a random 3D tensor (5x4x4)
T = torch.randn(5, 4, 4)
print(T)

# get a specific element
print(T[0, 1, 3])

# get the 1st 4x4 matrix
f = T[0, :, :]
print(f)

# alternatively, you can use an ellipsis
print(T[0, ...] == f)

tensor([[[-0.8776,  0.1318, -0.7440, -1.4104],
         [ 0.6585,  0.6290, -1.4942, -1.8423],
         [-0.5975, -0.3693, -0.3666,  0.5867],
         [-0.7993, -1.6542,  0.4487,  0.3821]],

        [[-0.6999, -0.6859,  0.1622,  0.2719],
         [ 0.1629,  1.2857,  1.7499, -0.3015],
         [-2.3864, -1.7819,  0.2345, -1.9478],
         [ 1.0991,  0.1065, -1.0103,  0.1808]],

        [[ 0.0476, -0.7155, -0.8256, -1.1160],
         [ 0.1879, -0.3157, -0.3544,  1.9277],
         [-0.9919,  0.0493,  0.8381, -0.4331],
         [-0.2990, -0.7263,  0.1466, -0.7470]],

        [[ 0.0644,  0.3997,  0.6627,  1.3289],
         [ 0.3653,  1.2827, -0.7431,  0.4097],
         [-0.7255, -0.7017, -1.1680,  0.4409],
         [ 0.6671,  0.3494, -0.0381, -0.2883]],

        [[-0.9123,  0.8269, -0.0548, -0.7141],
         [-1.3370, -0.2175, -1.0092, -1.0210],
         [-0.2294,  0.8048,  1.6038, -0.3209],
         [ 0.0713, -0.5752, -0.0336,  1.6073]]])
tensor(-1.8423)
tensor([[-0.8776,  0.1318, -0.7440